CREATE TABLE IF NOT EXISTS `annexure_subject_answer_value` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `aname` varchar(250) DEFAULT NULL,
  `N1` int(11) NOT NULL,
  `N2` int(11) NOT NULL,
  `N3` int(11) NOT NULL,
  `N4` int(11) NOT NULL,
  `N5` int(11) NOT NULL,
  `V1` varchar(250) NOT NULL,
  `V2` varchar(250) NOT NULL,
  `V3` varchar(250) NOT NULL,
  `V4` varchar(250) NOT NULL,
  `V5` varchar(250) NOT NULL,
  `D1` date DEFAULT NULL,
  `D2` date DEFAULT NULL,
  `D3` date DEFAULT NULL,
  `D4` date DEFAULT NULL,
  `D5` date DEFAULT NULL,
  `F1` double(15,2) NOT NULL,
  `F2` double(15,2) NOT NULL,
  `F3` double(15,2) NOT NULL,
  `F4` double(15,2) NOT NULL,
  `F5` double(15,2) NOT NULL,
  `T1` text NOT NULL,
  `T2` text NOT NULL,
  `T3` text NOT NULL,
  `T4` text NOT NULL,
  `T5` text NOT NULL,
  `col6` varchar(250) NOT NULL,
  `col7` varchar(250) NOT NULL,
  `col8` varchar(250) NOT NULL,
  `col9` varchar(250) NOT NULL,
  `col10` varchar(250) NOT NULL,
  `col11` varchar(250) NOT NULL,
  `col12` varchar(250) NOT NULL,
  `col13` varchar(250) NOT NULL,
  `col14` varchar(250) NOT NULL,
  `col15` varchar(250) NOT NULL,
  `clientid` int(11) NOT NULL,
  `assignmentid` int(11) NOT NULL,
  `domainid` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_date` date NOT NULL,
  `elementid` int(11) NOT NULL,
  `subjectid` int(11) NOT NULL,
  `annexureid` int(11) NOT NULL,
  `execution_id` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `approve` int(11) NOT NULL COMMENT '1=approve,0=notapproved',
  `approved_by` int(11) NOT NULL,
  `approved_on` date NOT NULL,
  `status` int(11) NOT NULL COMMENT ' 1=not initiated,2-submitted,3-rejected,4-approved ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
