CREATE TABLE IF NOT EXISTS `assignment_scheduler` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `activity_name` text NOT NULL,
  `activity_type` varchar(100) NOT NULL,
  `activity_id` int(11) DEFAULT NULL,
  `table_name` varchar(50) NOT NULL,
  `record_id` int(11) NOT NULL,
  `timeline_id` int(11) NOT NULL,
  `dur_hrs` varchar(10) NOT NULL,
  `est_start_date` date DEFAULT NULL,
  `est_end_date` date DEFAULT NULL,
  `es` int(11) NOT NULL,
  `ef` int(11) NOT NULL,
  `ls` int(11) NOT NULL,
  `lf` int(11) NOT NULL,
  `critical_path` varchar(4) NOT NULL COMMENT 'yes,no',
  `assignment_id` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` date DEFAULT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_on` date DEFAULT NULL,
  `taskHead_id` int(11) NOT NULL,
  `task_list_id` int(11) NOT NULL,
  `perc_val` varchar(100) NOT NULL,
  `workid` int(11) NOT NULL,
  `task_status` int(11) NOT NULL,
  `status_change_dt` datetime DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '1',
  `est_hrs` float(5,2) NOT NULL,
  `poc` double(5,2) NOT NULL,
  `avalue` double(10,2) NOT NULL,
  `applicability_answer` int(11) NOT NULL,
  `config_type` varchar(250) NOT NULL DEFAULT 'Manual' COMMENT 'Manual,Decisions,Audit Responses',
  `audit_response_id` int(11) NOT NULL,
  `arid` int(11) NOT NULL,
  `auditresponseid` int(11) NOT NULL,
  `task_head` int(11) NOT NULL,
  `milestone_type` int(11) NOT NULL COMMENT '1- SMM,2-SMT 3- Chapter',
  `seq_order` int(11) NOT NULL,
  `is_folder` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 - Non folder 1 folder',
  `sch_id` int(11) NOT NULL COMMENT 'parent folder id',
  `folder_items_id` int(11) NOT NULL COMMENT 'id for both folder and item id',
  `parent_id` int(11) NOT NULL,
  `seq_id` int(11) NOT NULL,
  `level_no` int(11) NOT NULL,
  `seq_no` int(10) NOT NULL,
  `Is_programmed` tinytext NOT NULL,
  `sum_planned_hrs` double(10,2) NOT NULL,
  `sum_performed_hrs` double(10,2) NOT NULL,
  `sum_score` double(10,2) NOT NULL,
  `sum_planned_value` double(10,2) NOT NULL,
  `sum_performance_value` double(10,2) NOT NULL,
  `ch_id` int(11) DEFAULT NULL,
  `ml_id` int(11) DEFAULT NULL,
  `to_id` int(11) DEFAULT NULL,
  `scoped_items` int(10) NOT NULL,
  `executed_items` int(10) NOT NULL,
  `approved_items` int(10) NOT NULL,
  `status_of_creation` int(2) DEFAULT NULL COMMENT '1=submited,2=approved',
  `review_status` int(11) NOT NULL,
  `perform_by` int(11) DEFAULT NULL,
  `perform_on` date DEFAULT NULL,
  `perform_ts` datetime DEFAULT NULL,
  `perform_note` text,
  `perform_status` int(11) NOT NULL,
  `review_by` int(11) DEFAULT NULL,
  `review_on` date DEFAULT NULL,
  `review_ts` datetime DEFAULT NULL,
  `review_note` text,
  `is_hidden` int(1) NOT NULL DEFAULT '0',
  `node_code` varchar(255) DEFAULT NULL,
  `node_level` int(11) DEFAULT NULL,
  `node_sequence` int(11) DEFAULT '0',
  `signoff_by` int(5) NOT NULL,
  `signoff_on` datetime DEFAULT NULL,
  `signoff_status` int(1) NOT NULL,
  `node_name` varchar(255) DEFAULT NULL,
  `parent_node_id` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `est_end_date` (`est_end_date`),
  KEY `activity_type` (`activity_type`),
  KEY `task_status` (`task_status`),
  KEY `assignment_id` (`assignment_id`),
  KEY `record_id` (`record_id`),
  KEY `timeline_id` (`timeline_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
