CREATE TABLE IF NOT EXISTS `inspection_data` (
  `id_id` int(11) NOT NULL AUTO_INCREMENT,
  `cid` int(11) NOT NULL,
  `pid` int(11) DEFAULT NULL,
  `milestone` int(11) NOT NULL,
  `form_type_structure` varchar(150) DEFAULT NULL,
  `form_type_structure_id` int(11) DEFAULT '0',
  `form_structure_id` int(11) NOT NULL DEFAULT '0',
  `ia_id` int(11) DEFAULT NULL,
  `report_date` varchar(255) DEFAULT NULL,
  `report_ref` text,
  `observation` text NOT NULL,
  `present_status` varchar(255) NOT NULL,
  `attachment` varchar(225) DEFAULT NULL,
  `compilance_status` varchar(225) NOT NULL COMMENT 'pending--pending,resolved--complied&closed,not resolved---not complied&closed',
  `approval_status` varchar(225) DEFAULT NULL,
  `location` int(11) DEFAULT NULL,
  `department` int(11) DEFAULT NULL,
  `check` varchar(255) DEFAULT NULL,
  `checklist` varchar(255) DEFAULT NULL,
  `element_id` int(11) DEFAULT NULL,
  `subject_id` int(11) DEFAULT NULL,
  `inspection_remarks_id` int(11) NOT NULL,
  `finding_type` int(11) NOT NULL,
  `created_user` int(11) NOT NULL,
  `compliance_user` int(11) NOT NULL,
  `approval_user` int(11) NOT NULL,
  `compliance_approver` int(11) NOT NULL,
  `compliance_approval_status` int(11) NOT NULL,
  `compliance_attachment` text NOT NULL,
  `compliance_observation` text NOT NULL,
  `status_approval` int(11) NOT NULL COMMENT '1=create user,2=approveuser,3=rejectuser,4=compilanceuser,5=compilanceuserApproval,6=confirm',
  `attachment_id` int(11) NOT NULL,
  `ass_seq_id` int(11) NOT NULL,
  `ass_seq_txt` varchar(15) NOT NULL,
  `page_type` int(11) NOT NULL COMMENT 'wpa,fss,coa,cos',
  `page_head_id` int(11) NOT NULL,
  `page_node_id` int(11) NOT NULL,
  `activity_risk_id` int(11) NOT NULL,
  `activity_control_id` int(11) NOT NULL,
  `ranking` int(11) NOT NULL,
  `consequences` text NOT NULL,
  `condition_text` text NOT NULL,
  `criteria` text NOT NULL,
  `cause` text NOT NULL,
  `corrective_action` text NOT NULL,
  `element_name` varchar(200) DEFAULT NULL,
  `subject_name` varchar(200) DEFAULT NULL,
  `head` int(11) DEFAULT NULL,
  `sub_head` int(11) DEFAULT NULL,
  `execution_id` int(11) DEFAULT NULL,
  `source_assignment` int(11) DEFAULT NULL,
  `role_forward` int(2) NOT NULL DEFAULT '0' COMMENT '1- role forwarded\r\n0 - not role forwarded',
  `role_forward_type` int(2) NOT NULL COMMENT '0- none, 1- to memo , 2- to finding by other',
  `status_of_finalization` int(2) NOT NULL DEFAULT '0' COMMENT '1- finalized',
  PRIMARY KEY (`id_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
