CREATE TABLE IF NOT EXISTS `inspection_remarks` (
  `irid` int(11) NOT NULL AUTO_INCREMENT,
  `inspection_agency_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `element_id` int(11) NOT NULL,
  `subject_id` int(11) NOT NULL,
  `short_note` varchar(250) NOT NULL,
  `description` text NOT NULL,
  `reference_txt` varchar(250) NOT NULL,
  `status` int(11) NOT NULL COMMENT '2-Approved,1-Pending,3-Rejected,4=notapproved',
  `compliance_status` int(11) NOT NULL COMMENT '1=Complied,2=not Complied',
  `created_by` int(11) NOT NULL,
  `approved_by` int(11) NOT NULL,
  `creation_dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_dt` date NOT NULL,
  `complyance_txt` text NOT NULL,
  `attachment` varchar(250) NOT NULL,
  `compilance_attachment` varchar(250) NOT NULL,
  `display_status` int(11) NOT NULL DEFAULT '1' COMMENT '1=active,0=inactive',
  `temp_code` varchar(250) NOT NULL,
  `attachment_id` int(11) NOT NULL,
  `status_approval` int(11) NOT NULL,
  `ass_seq_id` int(11) NOT NULL,
  `ass_seq_txt` varchar(15) NOT NULL,
  `inspection_agency_dummy` varchar(250) NOT NULL,
  `element_dummy` varchar(250) NOT NULL,
  `subject_dummy` varchar(250) NOT NULL,
  `element_name` varchar(200) NOT NULL,
  `subject_name` varchar(200) NOT NULL,
  `source_assignment` int(11) DEFAULT NULL,
  PRIMARY KEY (`irid`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
