CREATE TABLE IF NOT EXISTS `sms_works` (
  `work_id` int(11) NOT NULL AUTO_INCREMENT,
  `workseries` varchar(5) NOT NULL,
  `client_id` int(11) NOT NULL,
  `task_id` int(11) NOT NULL,
  `period_id` int(11) NOT NULL,
  `timeline_id` int(11) NOT NULL DEFAULT '0' COMMENT 'FK:timeline',
  `worktaskname` varchar(100) NOT NULL,
  `category_id` int(11) NOT NULL,
  `workstatus_id` int(11) NOT NULL,
  `workclosed_description` longtext NOT NULL,
  `status` varchar(15) NOT NULL DEFAULT 'active',
  `worktype` varchar(25) DEFAULT NULL COMMENT 'Defined,Undefined,Audits,Projects',
  `taskHead_id` int(11) NOT NULL,
  `task_structure_type` int(11) NOT NULL COMMENT '1-undefined,2-defined',
  `task_structure_id` int(11) NOT NULL,
  `works_creation_dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `plannedstartdate` date DEFAULT NULL,
  `plannedenddate` date DEFAULT NULL,
  `actualstartdate` date NOT NULL,
  `actualenddate` date NOT NULL,
  `value` varchar(50) DEFAULT NULL,
  `priority` varchar(15) NOT NULL,
  `createdby` int(11) NOT NULL,
  `description` text NOT NULL,
  `am_id` int(11) NOT NULL,
  `ru_id` int(11) NOT NULL COMMENT 'review user',
  `fss_head_id` int(11) NOT NULL,
  `coa_head_id` int(11) NOT NULL,
  `cos_head_id` int(11) NOT NULL,
  `prev_assignment` int(11) NOT NULL,
  `domain` int(11) NOT NULL,
  `branch_id` int(11) NOT NULL,
  `assignment_type` int(5) DEFAULT NULL,
  `sum_planned_hrs` double(10,2) NOT NULL,
  `sum_performed_hrs` double(10,2) NOT NULL,
  `sum_planned_value` double(10,2) NOT NULL,
  `sum_performance_value` double(10,2) NOT NULL,
  `sum_score` double(10,2) NOT NULL,
  `sum_dur_hrs` double(10,2) NOT NULL,
  `sum_value` double(10,2) NOT NULL,
  `financial_series` int(1) NOT NULL DEFAULT '0',
  `datacollection_analytics` int(1) NOT NULL DEFAULT '0',
  `internal_control_testing` int(1) NOT NULL DEFAULT '0',
  `automated_ledger_scrutiny` int(1) NOT NULL DEFAULT '0',
  `permanant_current_file` int(1) NOT NULL DEFAULT '0',
  `module_1` int(1) NOT NULL DEFAULT '0',
  `module_2` int(1) NOT NULL DEFAULT '0',
  `module_3` int(1) NOT NULL DEFAULT '0',
  `module_4` int(1) NOT NULL DEFAULT '0',
  `module_5` int(1) NOT NULL DEFAULT '0',
  `module_6` int(1) NOT NULL DEFAULT '0',
  `is_group` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 -- Individual 1-- Group assignment',
  `group_id` int(11) NOT NULL DEFAULT '0' COMMENT 'relation from group_assignments table',
  `group_sequence` tinyint(2) NOT NULL DEFAULT '0' COMMENT 'for sequencing assignments',
  `assignment_type_id` int(11) NOT NULL,
  `custom_type` int(2) DEFAULT '0' COMMENT '1- assignment_name custom',
  `is_consolidated` tinyint(1) NOT NULL DEFAULT '0',
  `is_fss` tinyint(1) DEFAULT '0' COMMENT '0:Not Required FSS 1: Required Fss',
  PRIMARY KEY (`work_id`),
  KEY `status` (`status`),
  KEY `client_id` (`client_id`),
  KEY `domain` (`domain`),
  KEY `is_fss` (`is_fss`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
