CREATE TABLE IF NOT EXISTS `compilancecalendar_subject_answer_value` (
  `value_id` int(11) NOT NULL AUTO_INCREMENT,
  `compilancecalendar_id` int(11) NOT NULL,
  `compilancecalendar_category_id` int(11) NOT NULL,
  `compilancecalendar_subcategory_id` int(11) NOT NULL,
  `answer` text NOT NULL,
  `ans_val` int(11) NOT NULL COMMENT '0-No,1-Yes',
  `given_by` int(11) NOT NULL,
  `execution_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `template_id` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `status` int(11) NOT NULL COMMENT '	1=not initiated,2-submitted,3-rejected,4-approved',
  `given_dt` date NOT NULL,
  `approved_by` int(11) NOT NULL,
  `approved_dt` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `actual_date` date NOT NULL,
  `compiled_by` varchar(250) NOT NULL,
  `proof` varchar(250) NOT NULL,
  `remarks` text NOT NULL,
  `is_applicable` tinyint(4) NOT NULL DEFAULT '1',
  `applicable_day` int(50) DEFAULT NULL,
  `applicable_date` date DEFAULT NULL,
  `timeline_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`value_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
