CREATE TABLE IF NOT EXISTS `sms_clients` (
  `client_id` int(11) NOT NULL AUTO_INCREMENT,
  `client_name` varchar(255) NOT NULL,
  `fileno` varchar(30) DEFAULT NULL,
  `client_email` varchar(100) NOT NULL,
  `client_pan` varchar(20) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `owner_name` varchar(100) NOT NULL,
  `owner_num` bigint(20) NOT NULL,
  `accountant_name` varchar(100) NOT NULL,
  `accountant_num` bigint(20) NOT NULL,
  `address` varchar(250) NOT NULL,
  `asgclient_id` int(11) NOT NULL,
  `status` varchar(10) NOT NULL,
  `created_by` int(11) NOT NULL,
  `client_creationdt` datetime NOT NULL,
  `domain_id` int(11) NOT NULL,
  `coa_head_id` int(11) NOT NULL,
  `cos_head_id` int(11) NOT NULL,
  `fss_head_id` int(11) NOT NULL,
  `branch_id` int(11) NOT NULL,
  `main_or_sub` tinyint(4) DEFAULT NULL,
  `assignment_id` int(11) DEFAULT NULL COMMENT 'its a dummy used for excel upload',
  `company_id` int(11) DEFAULT NULL COMMENT 'its a dummy used for excel upload',
  `nationality` varchar(30) NOT NULL,
  `website` varchar(100) NOT NULL,
  `contact_person` varchar(50) NOT NULL,
  `accounting_package` text NOT NULL,
  `registered_address` text NOT NULL,
  `cin` varchar(80) NOT NULL,
  `registration_no` varchar(30) NOT NULL,
  `iec` varchar(50) NOT NULL,
  `pf_reg_no` varchar(30) NOT NULL,
  `esi_reg_no` varchar(30) NOT NULL,
  `pt_reg_no` varchar(30) NOT NULL,
  `is_fss_updated` tinyint(4) NOT NULL DEFAULT '0',
  `is_repeated` int(10) NOT NULL,
  `is_cloned` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`client_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
