CREATE TABLE IF NOT EXISTS `fss_assignment_level` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `fss_client_level_id` int(11) NOT NULL COMMENT 'FK:fss_client_level',
  `client_id` int(11) NOT NULL COMMENT 'FK:sms_clients',
  `assignment_id` int(11) NOT NULL COMMENT 'FK:sms_works',
  `domain_id` int(11) DEFAULT NULL,
  `tb_net_self` decimal(20,2) DEFAULT '0.00',
  `tb_net_self_children` decimal(20,2) DEFAULT '0.00',
  `tb_opening_self` decimal(22,2) DEFAULT NULL,
  `tb_opening_self_children` decimal(22,2) DEFAULT NULL,
  `db_net_self` decimal(20,2) DEFAULT '0.00',
  `db_net_self_children` decimal(20,2) DEFAULT '0.00',
  `rectify_self` decimal(12,2) NOT NULL DEFAULT '0.00',
  `rectify_self_children` decimal(12,2) NOT NULL DEFAULT '0.00',
  `reclassify_self` decimal(12,2) NOT NULL DEFAULT '0.00',
  `reclassify_self_children` decimal(12,2) NOT NULL DEFAULT '0.00',
  `input_self` decimal(12,2) NOT NULL DEFAULT '0.00',
  `input_self_children` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total_self` decimal(12,2) NOT NULL DEFAULT '0.00',
  `total_self_children` decimal(12,2) NOT NULL DEFAULT '0.00',
  `risk_score` double(15,2) DEFAULT NULL,
  `open_risk_score` double(15,2) DEFAULT NULL,
  `control_score` double(15,2) DEFAULT NULL,
  `adjusted_self` decimal(22,2) DEFAULT NULL,
  `adjusted_self_children` decimal(22,2) DEFAULT NULL,
  `unadjusted_self` decimal(22,2) DEFAULT NULL,
  `unadjusted_self_children` decimal(22,2) DEFAULT NULL,
  `specific_materiality` double(15,2) DEFAULT NULL,
  `effective_materiality` double(15,2) DEFAULT NULL,
  `mark_as_addressed` int(11) DEFAULT '0' COMMENT '1,0',
  `print_notes` text,
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `assignment_id` (`assignment_id`),
  KEY `client_id` (`client_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
