CREATE TABLE IF NOT EXISTS `fss_chartofaccounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gl_name` varchar(100) DEFAULT NULL,
  `gl_code` varchar(100) DEFAULT NULL,
  `fss_client_level_id` int(10) DEFAULT NULL COMMENT 'FK:fss_client_level',
  `remarks` text,
  `client_id` int(10) NOT NULL COMMENT 'FK:sms_clients',
  `domain_id` int(10) NOT NULL,
  `batch_id` int(10) DEFAULT NULL,
  `created_by` int(10) NOT NULL,
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_by` int(11) NOT NULL,
  `is_active` int(10) DEFAULT '1' COMMENT '0:inactive,1:active',
  `is_party` tinyint(4) DEFAULT NULL,
  `fss_group_id` int(11) DEFAULT NULL COMMENT 'FK:fss_groups',
  `fss_group_name` varchar(255) DEFAULT NULL,
  `assignment_id` int(11) DEFAULT '0' COMMENT 'FK:sms_works',
  `master_it_tds` varchar(255) DEFAULT NULL,
  `master_gst` varchar(255) DEFAULT NULL,
  `consd_as_party` varchar(255) DEFAULT NULL,
  `spl_cat` varchar(255) DEFAULT NULL,
  `falling_under_gl_id` int(11) DEFAULT NULL,
  `falling_under_gl_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `gl_name` (`gl_name`,`client_id`,`falling_under_gl_id`) USING BTREE,
  KEY `client_id` (`client_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
