CREATE TABLE IF NOT EXISTS `fss_client_level` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fss_head_id` int(11) NOT NULL COMMENT 'FK:fss_heads',
  `client_id` int(11) NOT NULL COMMENT 'FK:sms_clients',
  `short_name` varchar(100) NOT NULL,
  `full_name` text,
  `parent_node_id` int(11) DEFAULT NULL,
  `base_node_id` int(11) DEFAULT NULL,
  `major_id` int(3) NOT NULL DEFAULT '0' COMMENT '1:Liabilities,2:Assets,3:Incomes,4:Expenses',
  `minor_id` int(3) NOT NULL COMMENT 'FK:fss_minors',
  `polarity` tinyint(1) NOT NULL DEFAULT '1',
  `permanent_id` int(3) NOT NULL DEFAULT '0' COMMENT 'FK:fss_permanents',
  `node_level` int(11) DEFAULT NULL,
  `node_sequence` int(11) DEFAULT NULL,
  `node_code` varchar(250) DEFAULT NULL,
  `fss_master_node_id` int(11) DEFAULT NULL,
  `fss_master_node_name` varchar(100) DEFAULT NULL,
  `fss_master_node_parent_id` int(11) DEFAULT NULL,
  `fss_master_node_sequence` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `is_active` int(1) DEFAULT NULL COMMENT '1=active,0=inactive',
  `prev_link_id` int(11) DEFAULT NULL,
  `master_link_id` int(11) DEFAULT NULL,
  `master_base_node_id` int(11) DEFAULT '0',
  `is_face` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 : show 1: hide',
  `is_terminal_node` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 : show 1: hide',
  `child_count` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `is_face` (`is_face`),
  KEY `is_terminal_node` (`is_terminal_node`),
  KEY `minor_id` (`minor_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
