CREATE TABLE IF NOT EXISTS `fss_masters` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fss_head_id` int(11) NOT NULL COMMENT 'FK:fss_heads',
  `short_name` varchar(100) NOT NULL,
  `full_name` text,
  `parent_node_id` int(11) DEFAULT NULL,
  `base_node_id` int(11) DEFAULT NULL,
  `major_id` int(3) NOT NULL DEFAULT '0' COMMENT '1:Liabilities,2:Assets,3:Incomes,4:Expenses',
  `minor_id` int(3) NOT NULL COMMENT 'FK:fss_minors',
  `polarity` tinyint(1) NOT NULL DEFAULT '1',
  `permanent_id` int(3) NOT NULL DEFAULT '0' COMMENT 'FK:fss_permanents',
  `node_level` int(5) DEFAULT NULL,
  `node_sequence` int(11) DEFAULT NULL,
  `node_code` varchar(250) DEFAULT NULL,
  `admin_node_id` int(11) DEFAULT NULL,
  `admin_node_name` varchar(100) DEFAULT NULL,
  `admin_node_parent_id` int(11) DEFAULT NULL,
  `admin_node_sequence` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `is_face` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:show 1:hide',
  `is_terminal_node` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:show 1:hide',
  `duration` int(11) NOT NULL DEFAULT '0',
  `duration_children` int(11) NOT NULL DEFAULT '0',
  `duration_self_plus_children` int(11) NOT NULL DEFAULT '0',
  `child_count` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fss_head_id` (`fss_head_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
