CREATE TABLE IF NOT EXISTS `fss_minors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `minor_name` varchar(100) NOT NULL,
  `polarity` tinyint(4) DEFAULT '1',
  `permanent_id` int(1) DEFAULT '0',
  `bs_pl` int(11) DEFAULT NULL COMMENT '1=bs,2=pl',
  `major` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `status` int(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=134 DEFAULT CHARSET=utf8;



INSERT INTO `fss_minors` (`id`, `minor_name`, `polarity`, `permanent_id`, `bs_pl`, `major`, `created_by`, `created_on`, `status`) VALUES
(1, 'Equity and Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(2, 'Shareholder\'s Funds', -1, 0, 1, 1, NULL, NULL, 0),
(3, 'Shareholder\'s Funds_Share Capital', -1, 0, 1, 1, NULL, NULL, 0),
(4, 'Share Capital_ Authorised Share Capital', -1, 0, 1, 1, NULL, NULL, 0),
(5, 'Share Capital_ Issued Share Capital', -1, 0, 1, 1, NULL, NULL, 0),
(6, 'Share Capital_ Paid up Share Capital', -1, 0, 1, 1, NULL, NULL, 0),
(7, 'Shareholders Funds_Reserves and Surplus', -1, 0, 1, 1, NULL, NULL, 0),
(8, 'Reserves and Surplus_Revaluation Reserve', -1, 0, 1, 1, NULL, NULL, 0),
(9, 'Reserves and Surplus_Capital Reserve', -1, 0, 1, 1, NULL, NULL, 0),
(10, 'Reserves and Surplus_Redemption Reserves', -1, 0, 1, 1, NULL, NULL, 0),
(11, 'Reserves and Surplus_ Profit', -1, 0, 1, 1, NULL, NULL, 0),
(12, 'Reserves and Surplus_ Other Reserves', -1, 0, 1, 1, NULL, NULL, 0),
(13, 'Share Application money  pending allotment', -1, 0, 1, 1, NULL, NULL, 0),
(14, 'Non current liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(15, 'Non current liabilities_Long term borrowings', -1, 0, 1, 1, NULL, NULL, 0),
(16, 'Long term borrowings_ Long term borrowings from banks', -1, 0, 1, 1, NULL, NULL, 0),
(17, 'Long term borrowings_ Long term borrowings from others', -1, 0, 1, 1, NULL, NULL, 0),
(18, 'Non Current Liabilities_ Deferred Tax Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(19, 'Non Current Liabilities_Financial Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(20, 'Non Current Financial Liabilities_Lease Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(21, 'Non Current Liabilities_Long Term Provisions', -1, 0, 1, 1, NULL, NULL, 0),
(22, 'Long Term Provisions_Provision for Employee benefits', -1, 0, 1, 1, NULL, NULL, 0),
(23, 'Long Term Provisions_Other Provisions', -1, 0, 1, 1, NULL, NULL, 0),
(24, 'Long Term Provisions_Accumulated Depreciation', -1, 0, 1, 1, NULL, NULL, 0),
(25, 'Non Current Liabilities_Other Long Term Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(26, 'Other Long Term Liabilities_Non-Current  payables', -1, 0, 1, 1, NULL, NULL, 0),
(27, 'Other Long Term Liabilities_ Others', -1, 0, 1, 1, NULL, NULL, 0),
(28, 'Current Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(29, 'Current Liabilities_Short term borrowings', -1, 0, 1, 1, NULL, NULL, 0),
(30, 'Short term borrowings_ Short term borrowings from banks', -1, 0, 1, 1, NULL, NULL, 0),
(31, 'Short term borrowings _ Short term borrowings from others', -1, 0, 1, 1, NULL, NULL, 0),
(32, 'Short term borrowings_Deposits', -1, 0, 1, 1, NULL, NULL, 0),
(33, 'Current Liabilities_ Trade payables', -1, 0, 1, 1, NULL, NULL, 0),
(34, 'Current Liabilities_Financial Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(35, 'Financial Liabilities_Lease liabilites', -1, 0, 1, 1, NULL, NULL, 0),
(36, 'Current Liabilities_Advances Received', -1, 0, 1, 1, NULL, NULL, 0),
(37, 'Advances received_ Advances received for goods', -1, 0, 1, 1, NULL, NULL, 0),
(38, 'Advances received_ Advances received for services', -1, 0, 1, 1, NULL, NULL, 0),
(39, 'Current Liabilites_Other Current Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(40, 'Other Current Liabilities_ Unpaid dividends', -1, 0, 1, 1, NULL, NULL, 0),
(41, 'Other Current Liabilities_ Unbilled revenue', -1, 0, 1, 1, NULL, NULL, 0),
(42, 'Other Current Liabilities_ Provision for expenses', -1, 0, 1, 1, NULL, NULL, 0),
(43, 'Other Current Liabilities_ Other Current Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(44, 'Current Liabilities_Statutory Liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(45, 'Statutory Liabilities_ GST output tax liability', -1, 0, 1, 1, NULL, NULL, 0),
(46, 'Statutory Liabilities_ Income Tax payable', -1, 0, 1, 1, NULL, NULL, 0),
(47, 'Statutory Liabilities_ TDS payable', -1, 0, 1, 1, NULL, NULL, 0),
(48, 'Statutory Liabilities_ Other statutory liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(49, 'Current Liabilities_Short Term Provisions', -1, 0, 1, 1, NULL, NULL, 0),
(50, 'Short term provisions_Provision for Employee benefits', -1, 0, 1, 1, NULL, NULL, 0),
(51, 'Short term provisions_Provision for Debtors', -1, 0, 1, 1, NULL, NULL, 0),
(52, 'Short term provisions_Other Provisions', -1, 0, 1, 1, NULL, NULL, 0),
(53, 'Contingent liabilities', -1, 0, 1, 1, NULL, NULL, 0),
(54, 'Assets', 1, 0, 1, 2, NULL, NULL, 0),
(55, 'Non-current Assets', 1, 0, 1, 2, NULL, NULL, 0),
(56, 'Non-current Assets_ Property, plant and equipment', 1, 0, 1, 2, NULL, NULL, 0),
(57, 'Non-current Assets_Investment Property', 1, 0, 1, 2, NULL, NULL, 0),
(58, 'Non-current Assets_Biological Assets', 1, 0, 1, 2, NULL, NULL, 0),
(59, 'Non-current Assets_Intangible Assets', 1, 0, 1, 2, NULL, NULL, 0),
(60, 'Non-Current Assets_ Other Intangible Assets', 1, 0, 1, 2, NULL, NULL, 0),
(61, 'Non-Current Assets_ Goodwill', 1, 0, 1, 2, NULL, NULL, 0),
(62, 'Non-Current Assets_ Capital Work in Progress', 1, 0, 1, 2, NULL, NULL, 0),
(63, 'Non-Current Assets_ Intangible assets under development', 1, 0, 1, 2, NULL, NULL, 0),
(64, 'Non-Current Assets_ Non Current Investments', 1, 0, 1, 2, NULL, NULL, 0),
(65, 'Non-Current Assets_ Deferred Tax assets', 1, 0, 1, 2, NULL, NULL, 0),
(66, 'Non-Current Assets_ Non-current receivables', 1, 0, 1, 2, NULL, NULL, 0),
(67, 'Non-Current Assets_Long term loans and advances', 1, 0, 1, 2, NULL, NULL, 0),
(68, 'Non-Current Assets_ Other non-current assets', 1, 0, 1, 2, NULL, NULL, 0),
(69, 'Non-current Assets_Financial Assets', 1, 0, 1, 2, NULL, NULL, 0),
(70, 'Current Assets', 1, 0, 1, 2, NULL, NULL, 0),
(71, 'Current Assets_ Short term investments', 1, 0, 1, 2, NULL, NULL, 0),
(72, 'Current Assets_Cash and Cash Equivalents', 1, 0, 1, 2, NULL, NULL, 0),
(73, 'Cash and cash equivalents_ Cash', 1, 0, 1, 2, NULL, NULL, 0),
(74, 'Cash and cash equivalents_ Balances with banks', 1, 0, 1, 2, NULL, NULL, 0),
(75, 'Current Assets_ Current inventories', 1, 0, 1, 2, NULL, NULL, 0),
(76, 'Current inventories_Raw Materials', 1, 0, 1, 2, NULL, NULL, 0),
(77, 'Current inventories_Work in progress', 1, 0, 1, 2, NULL, NULL, 0),
(78, 'Current inventories_Finished Goods', 1, 0, 1, 2, NULL, NULL, 0),
(79, 'Current Assets_ Current trade receivables', 1, 0, 1, 2, NULL, NULL, 0),
(80, 'Current Assets_Financial Assets', 1, 0, 1, 2, NULL, NULL, 0),
(81, 'Current Assets_Other Current Assets', 1, 0, 1, 2, NULL, NULL, 0),
(82, 'Other Current Assets_ GST Input Balance', 1, 0, 1, 2, NULL, NULL, 0),
(83, 'Other Current Assets_ TDS receivable', 1, 0, 1, 2, NULL, NULL, 0),
(84, 'Other Current Assets_ Advance Tax', 1, 0, 1, 2, NULL, NULL, 0),
(85, 'Other Current Assets_ GST- refund receivable', 1, 0, 1, 2, NULL, NULL, 0),
(86, 'Other Current Assets_ Advances Given', 1, 0, 1, 2, NULL, NULL, 0),
(87, 'Other Current Assets_ Other Current Assets', 1, 0, 1, 2, NULL, NULL, 0),
(88, 'Incomes', -1, 0, 2, 3, NULL, NULL, 0),
(89, 'Incomes_Revenue from operations', -1, 0, 2, 3, NULL, NULL, 0),
(90, 'Incomes_ Revenue from operations-MFG', -1, 0, 2, 3, NULL, NULL, 0),
(91, 'Incomes_ Revenue from operations-Trading', -1, 0, 2, 3, NULL, NULL, 0),
(92, 'Revenue from Operations_Interest Earned', -1, 0, 2, 3, NULL, NULL, 0),
(93, 'Incomes_Other Comprehensive Income (OCI)', -1, 0, 2, 3, NULL, NULL, 0),
(94, 'Incomes_Non Operational Revenue', -1, 0, 2, 3, NULL, NULL, 0),
(95, 'Non-Operational Revenue_ Dividend income', -1, 0, 2, 3, NULL, NULL, 0),
(96, 'Non-Operational Revenue_ Interest income', -1, 0, 2, 3, NULL, NULL, 0),
(97, 'Non-Operational Revenue_ Net gain in sale of investments', -1, 0, 2, 3, NULL, NULL, 0),
(98, 'Non-Operational Revenue_ Other non-operating income', -1, 0, 2, 3, NULL, NULL, 0),
(99, 'Incomes_ Exceptional Income', -1, 0, 2, 3, NULL, NULL, 0),
(100, 'Expenses', 1, 0, 2, 4, NULL, NULL, 0),
(101, 'Expenses_Change in Inventory ', 1, 4, 2, 4, NULL, NULL, 1),
(102, 'Expenses_Cost of Material Consumed', 1, 3, 2, 4, NULL, NULL, 1),
(103, 'Expenses_ Purchases', 1, 0, 2, 4, NULL, NULL, 0),
(104, 'Expenses_ Opening Stock', 1, 0, 2, 4, NULL, NULL, 0),
(105, 'Expenses_ Closing Stock', 1, 5, 2, 4, NULL, NULL, 1),
(106, 'Expenses_Operating Expenses', 1, 0, 2, 4, NULL, NULL, 0),
(107, 'Expense_ Operating expenses- MFG', 1, 0, 2, 4, NULL, NULL, 0),
(108, 'Expense_ Operating expenses- Trading', 1, 0, 2, 4, NULL, NULL, 0),
(109, 'Expense_ Depreciation and amortization', 1, 0, 2, 4, NULL, NULL, 0),
(110, 'Expense_Impairment', 1, 0, 2, 4, NULL, NULL, 0),
(111, 'Expenses_Non Operating Expenses', 1, 0, 2, 4, NULL, NULL, 0),
(112, 'Non Operating Expenses_ Other Non-Operating Expenses', 1, 0, 2, 4, NULL, NULL, 0),
(113, 'Non Operating Expenses_Finance Costs', 1, 0, 2, 4, NULL, NULL, 0),
(114, 'Finance costs_ Interest expense', 1, 0, 2, 4, NULL, NULL, 0),
(115, 'Finance costs_ Other borrowing costs', 1, 0, 2, 4, NULL, NULL, 0),
(116, 'Finance costs_ Net loss on foreign currency transactions and translation', 1, 0, 2, 4, NULL, NULL, 0),
(117, 'Finance costs_ Other finance costs', 1, 0, 2, 4, NULL, NULL, 0),
(118, 'Non Operating Expenses_Tax Expense', 1, 0, 2, 4, NULL, NULL, 0),
(119, 'Tax expense_ Current tax', 1, 0, 2, 4, NULL, NULL, 0),
(120, 'Tax expense_ Deferred Tax', 1, 0, 2, 4, NULL, NULL, 0),
(121, 'Non Operating Expenses_Other expenses', 1, 0, 2, 4, NULL, NULL, 0),
(122, 'Expense_ Discontinued Operations', 1, 0, 2, 4, NULL, NULL, 0),
(123, 'Expense_ Exceptional Expense', 1, 0, 2, 4, NULL, NULL, 0),
(124, 'Non Operating Expenses_Employee Benefit expense', 1, 0, 2, 4, NULL, NULL, 0),
(125, 'Other non-current Assets_other non-current Assets', 1, 0, 1, 2, NULL, NULL, 0),
(126, 'Non-Current Investments_other non-current investments', 1, 0, 1, 2, NULL, NULL, 0),
(127, 'Short term investments_other short term Investments', 1, 0, 1, 2, NULL, NULL, 0),
(128, 'Money received against share warrants', -1, 0, 1, 1, NULL, NULL, 0),
(129, 'Current inventories_others', 1, 0, 1, 2, NULL, NULL, 0),
(130, 'Property, plant and equipment_Land', 1, 0, 1, 2, NULL, NULL, 0),
(131, 'Property, plant and equipment_others', 1, 0, 1, 2, NULL, NULL, 0),
(132, 'Profit Transferred  To Balance Sheet', 1, 1, 2, 6, NULL, NULL, 1),
(133, 'Profit Transferred From Profit and Loss', -1, 2, 1, 5, NULL, NULL, 1);
COMMIT;
