CREATE TABLE IF NOT EXISTS `fss_parameter` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `current_year_heading` varchar(50) NOT NULL,
  `previous_current_year_heading` varchar(50) NOT NULL,
  `prv_current_year_heading` varchar(50) NOT NULL,
  `previous_prv_current_year_heading` varchar(50) NOT NULL,
  `denomination_amounts` varchar(50) NOT NULL,
  `previous_denomination_amounts` varchar(50) NOT NULL,
  `balance_sheet_heading` varchar(50) NOT NULL,
  `previous_balance_sheet_heading` varchar(50) NOT NULL,
  `SOPL_heading` varchar(50) NOT NULL,
  `previous_SOPL_heading` varchar(50) NOT NULL,
  `cash_flow_heading` varchar(50) NOT NULL,
  `previous_cash_flow_heading` varchar(50) NOT NULL,
  `name_firm` varchar(100) NOT NULL,
  `previous_name_firm` varchar(100) NOT NULL,
  `frn` varchar(50) NOT NULL,
  `previous_frn` varchar(50) NOT NULL,
  `Sigining_patner` varchar(100) NOT NULL,
  `previous_Sigining_patner` varchar(100) NOT NULL,
  `membership_no` varchar(50) NOT NULL,
  `previous_membership_no` varchar(50) NOT NULL,
  `director1_name` varchar(100) NOT NULL,
  `previous_director1_name` varchar(100) NOT NULL,
  `designation_director1_name` varchar(50) NOT NULL,
  `previous_designation_director1_name` varchar(50) NOT NULL,
  `director2_name` varchar(100) NOT NULL,
  `previous_director2_name` varchar(100) NOT NULL,
  `designation_director2_name` varchar(50) NOT NULL,
  `previous_designation_director2_name` varchar(50) NOT NULL,
  `date_fss` date NOT NULL,
  `previous_date_fss` date NOT NULL,
  `place_fss` varchar(100) NOT NULL,
  `previous_place_fss` varchar(100) NOT NULL,
  `date_agm` date NOT NULL,
  `previous_date_agm` date NOT NULL,
  `date_issuance` date NOT NULL,
  `previous_date_issuance` date NOT NULL,
  `client` int(11) NOT NULL,
  `assignment` int(11) NOT NULL,
  `domain` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_date` date NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_on` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
