CREATE TABLE IF NOT EXISTS `userwork_plan` (
  `planid` int(11) NOT NULL AUTO_INCREMENT,
  `description` longtext NOT NULL,
  `estimatedhrs` float(5,2) NOT NULL,
  `clientid` int(11) DEFAULT NULL,
  `locid` int(11) NOT NULL,
  `ondate` date NOT NULL,
  `userid` int(11) NOT NULL,
  `plannedby` int(11) NOT NULL DEFAULT '-9',
  `first_plan_ondate` date NOT NULL,
  `superiorid` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `approvedby` int(11) NOT NULL DEFAULT '0' COMMENT '0:default',
  `entereddt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `refid` varchar(10) NOT NULL,
  `tasklistid` int(11) NOT NULL,
  `ulevel` varchar(5) NOT NULL,
  `planstatus` varchar(15) NOT NULL DEFAULT 'opened' COMMENT 'opened,closed',
  `type_of_plan` varchar(50) NOT NULL,
  `nature_of_plan` varchar(50) NOT NULL,
  `dependence_id` int(11) NOT NULL,
  `workid` int(11) NOT NULL,
  `record_status` varchar(15) NOT NULL DEFAULT 'active' COMMENT 'active,inactive',
  `value` varchar(10) NOT NULL,
  `attachment` varchar(250) NOT NULL,
  `attachment_id` varchar(250) NOT NULL,
  `domain` int(11) NOT NULL,
  `type_plan` varchar(250) NOT NULL DEFAULT 'Normal' COMMENT 'Normal,Approving',
  `reference_planid` int(11) NOT NULL,
  `holiday_id` int(11) NOT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `dataset_id` int(11) NOT NULL DEFAULT '0',
  `record_id` int(11) NOT NULL DEFAULT '0',
  `timeline_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`planid`),
  KEY `workid` (`workid`),
  KEY `ondate` (`ondate`),
  KEY `userid` (`userid`),
  KEY `domain` (`domain`),
  KEY `tasklistid` (`tasklistid`),
  KEY `planstatus` (`planstatus`),
  KEY `clientid` (`clientid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
