CREATE TABLE IF NOT EXISTS `tasklist` (
  `task_list_id` int(11) NOT NULL AUTO_INCREMENT,
  `task_head` int(11) NOT NULL,
  `parent_nodeid` int(11) NOT NULL,
  `short_task` text NOT NULL,
  `full_task` text NOT NULL,
  `nodelevel` int(11) NOT NULL,
  `nodecode` varchar(80) NOT NULL,
  `level1` int(11) NOT NULL,
  `level2` int(11) NOT NULL,
  `level3` int(11) NOT NULL,
  `level4` int(11) NOT NULL,
  `level5` int(11) NOT NULL,
  `conclusion` text NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '1=active,2=inactive',
  `status_approval` int(11) NOT NULL COMMENT '1=approved,2=not approved',
  `updated_on` datetime NOT NULL,
  `approved_by` int(11) NOT NULL,
  `approved_on` datetime NOT NULL,
  `perc_val` varchar(250) NOT NULL,
  `start_day` int(11) NOT NULL,
  `duration_days` int(11) NOT NULL,
  `duration_hrs` double(10,2) NOT NULL,
  `master_id` int(11) NOT NULL,
  `master_parent_id` int(11) NOT NULL,
  `chapter_id` int(11) NOT NULL,
  PRIMARY KEY (`task_list_id`),
  KEY `task_head` (`task_head`),
  KEY `parent_nodeid` (`parent_nodeid`),
  KEY `task_list_id` (`task_list_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
