CREATE TABLE IF NOT EXISTS `app_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `userid` varchar(50) NOT NULL,
  `pwd` varchar(250) NOT NULL,
  `userphoto` varchar(250) NOT NULL,
  `phone` bigint(20) NOT NULL,
  `hr_value` double(8,2) NOT NULL,
  `levels` varchar(10) NOT NULL,
  `reguser_id` int(11) NOT NULL,
  `status` char(15) NOT NULL DEFAULT 'active' COMMENT 'active,inactive',
  `creation_dt` datetime NOT NULL,
  `domain_id` int(11) NOT NULL,
  `profile_pic` varchar(250) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password_updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_id` int(11) NOT NULL,
  `branch_office_id` int(11) NOT NULL,
  `license_pack_id` varchar(250) NOT NULL,
  `report_to` int(11) NOT NULL DEFAULT '0',
  `gender` int(1) NOT NULL COMMENT '1=Male,2=Female',
  `dob` date NOT NULL,
  `pan_no` varchar(25) NOT NULL,
  `aadhar_no` varchar(30) NOT NULL,
  `blood_group` varchar(8) NOT NULL,
  `mobile_2` int(12) NOT NULL,
  `email_2` varchar(60) NOT NULL,
  `address` text NOT NULL,
  `father_name` varchar(60) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `userid` (`userid`),
  UNIQUE KEY `userid_2` (`userid`)
) ENGINE=InnoDB AUTO_INCREMENT=452 DEFAULT CHARSET=latin1;
