CREATE TABLE IF NOT EXISTS `kob_shareholder` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ass_seq_id` int(11) NOT NULL,
  `ass_seq_txt` varchar(15) NOT NULL,
  `name_shareholder` varchar(250) NOT NULL,
  `per_shareholder_earlier` varchar(50) NOT NULL,
  `per_shareholder_now` varchar(200) NOT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` varchar(250) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` date NOT NULL,
  `date_change` date NOT NULL,
  `type_change` varchar(200) NOT NULL,
  `attachment_id` int(11) DEFAULT NULL,
  `approved` tinyint(4) NOT NULL,
  `approved_by` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
