CREATE TABLE IF NOT EXISTS `p_inv_quantitative_details` (
  `qid` int(11) NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) NOT NULL,
  `name` varchar(250) NOT NULL,
  `category` enum('RawMaterials','FinishedGoods','Working progress') NOT NULL,
  `uom` varchar(50) NOT NULL,
  `opening_qty` double(8,2) NOT NULL,
  `opening_val` double NOT NULL,
  `purchase_qty` double(10,2) NOT NULL,
  `purchase_val` double NOT NULL,
  `produced_qty` double(10,2) NOT NULL,
  `produced_val` double NOT NULL,
  `transferred_in_qty` double(8,2) NOT NULL,
  `transferred_in_val` double NOT NULL,
  `consumed_qty` double(8,2) NOT NULL,
  `consumed_val` double NOT NULL,
  `sold_qty` double(8,2) NOT NULL,
  `sold_val` double NOT NULL,
  `transferred_out_qty` double(8,2) NOT NULL,
  `transferred_out_val` double NOT NULL,
  `closing_qty` double(8,2) NOT NULL,
  `closing_val` double NOT NULL,
  `physical_verification_qty` double(8,2) NOT NULL,
  `physical_verification_val` double NOT NULL,
  `shortage_excess_qty` double(8,2) NOT NULL,
  `shortage_excess_val` double NOT NULL,
  `remarks` text NOT NULL,
  `doer_user` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  PRIMARY KEY (`qid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
