CREATE TABLE IF NOT EXISTS `dc_legal_suits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_no` varchar(50) DEFAULT NULL,
  `gl_no` varchar(80) DEFAULT NULL,
  `customer_no` varchar(50) DEFAULT NULL,
  `customer_name` varchar(80) DEFAULT NULL,
  `branch_name` varchar(20) DEFAULT NULL,
  `customer_constitution` varchar(80) DEFAULT NULL,
  `customer_constitution_id` int(5) DEFAULT NULL,
  `emi_start_date` date DEFAULT NULL,
  `emi_total_nos` int(5) DEFAULT NULL,
  `emi_due` int(5) DEFAULT NULL,
  `emi_paid` int(5) DEFAULT NULL,
  `emi_overdue` int(5) DEFAULT NULL,
  `emi_closing_date` date DEFAULT NULL,
  `emi_type` varchar(50) DEFAULT NULL,
  `emi_type_id` int(5) DEFAULT NULL,
  `name` varchar(250) DEFAULT NULL,
  `dt_of_suit` date DEFAULT NULL,
  `name_of_court` varchar(250) DEFAULT NULL,
  `nature_of_suit` text,
  `name_of_counterpart` varchar(250) DEFAULT NULL,
  `amount` double(20,2) DEFAULT NULL,
  `present_status_of_suit` text,
  `amount_of_deposit` double(20,2) DEFAULT NULL,
  `amount_of_provision` double(20,2) DEFAULT NULL,
  `remarks` text,
  `strata_A` int(11) DEFAULT NULL,
  `strata_B` int(11) DEFAULT NULL,
  `strata_C` int(11) DEFAULT NULL,
  `strata_D` int(11) DEFAULT NULL,
  `strata_E` int(11) DEFAULT NULL,
  `filter_l` int(11) DEFAULT NULL,
  `filter_m` int(11) DEFAULT NULL,
  `filter_n` int(11) DEFAULT NULL,
  `filter_o` int(11) DEFAULT NULL,
  `filter_p` int(11) DEFAULT NULL,
  `materiality` int(11) DEFAULT NULL,
  `batchno` int(11) DEFAULT NULL,
  `temp_code` varchar(250) DEFAULT NULL,
  `assignment_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `domain_id` int(11) DEFAULT NULL,
  `status_of_approval` int(11) DEFAULT NULL,
  `status_active` int(11) DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `creation_dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approved_by` int(11) DEFAULT NULL,
  `approved_on` datetime DEFAULT NULL,
  `other1` varchar(250) DEFAULT NULL,
  `other2` text,
  `other3` date DEFAULT NULL,
  `ass_seq_id` int(11) DEFAULT NULL,
  `ass_seq_txt` varchar(15) DEFAULT NULL,
  `sanctioned_date` date DEFAULT NULL,
  `product_name` varchar(200) DEFAULT NULL,
  `product_id` int(5) DEFAULT NULL,
  `scheme_name` varchar(200) DEFAULT NULL,
  `scheme_id` int(5) DEFAULT NULL,
  `sector_name` varchar(200) DEFAULT NULL,
  `sector_id` int(5) DEFAULT NULL,
  `irac_name` varchar(200) DEFAULT NULL,
  `irac_id` int(5) DEFAULT NULL,
  `priority_name` varchar(200) DEFAULT NULL,
  `priority_id` int(5) DEFAULT NULL,
  `facility_name` varchar(200) DEFAULT NULL,
  `facility_id` int(5) DEFAULT NULL,
  `sanctioned_amount` double(20,2) DEFAULT NULL,
  `outstanding_amount` double(20,2) DEFAULT NULL,
  `overdue_amount` double(20,2) DEFAULT NULL,
  `accrued_interest_amount` double(20,2) DEFAULT NULL,
  `drawing_power_amount` double(20,2) DEFAULT NULL,
  `theoritical_balance_amount` double(20,2) DEFAULT NULL,
  `charge_type` varchar(80) DEFAULT NULL,
  `primary_security_amount` double(20,2) DEFAULT NULL,
  `primary_security_valuation_date` date DEFAULT NULL,
  `collateral_security_amount` double(20,2) DEFAULT NULL,
  `collateral_security_valuation_date` date DEFAULT NULL,
  `tangible_security_amount` double(20,2) DEFAULT NULL,
  `securedby_government_garantee` varchar(200) DEFAULT NULL,
  `securedby_other_garantee` varchar(200) DEFAULT NULL,
  `securedby_deposits` double(20,2) DEFAULT NULL,
  `unsecured_amount` double(20,2) DEFAULT NULL,
  `insurance_amount` double(20,2) DEFAULT NULL,
  `insurance_expiry_date` date DEFAULT NULL,
  `debit_summation` double(20,2) DEFAULT NULL,
  `interest_summation` double(20,2) DEFAULT NULL,
  `credit_summation` double(20,2) DEFAULT NULL,
  `irregular_days_summation` double(20,2) DEFAULT NULL,
  `internal_credit_rating` double(20,2) DEFAULT NULL,
  `external_credit_rating` double(20,2) DEFAULT NULL,
  `opening_internal_credit_rating` varchar(200) DEFAULT NULL,
  `closing_external_credit_rating` varchar(200) DEFAULT NULL,
  `roi` int(5) DEFAULT NULL,
  `type_interest` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `assignment_id` (`assignment_id`),
  KEY `assignment_id_2` (`assignment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
