CREATE TABLE IF NOT EXISTS `audit_notes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `note_number` varchar(55) NOT NULL,
  `element_id` int(55) DEFAULT NULL,
  `subject_id` int(11) DEFAULT NULL,
  `element_name` varchar(255) DEFAULT NULL,
  `subject_name` varchar(255) DEFAULT NULL,
  `milestone_id` int(11) DEFAULT NULL,
  `qs_id` varchar(255) DEFAULT NULL,
  `proposal_id` int(11) DEFAULT NULL,
  `user_type` int(11) DEFAULT NULL,
  `originator` int(11) DEFAULT NULL,
  `domain` int(11) DEFAULT NULL,
  `attachment_id` int(11) DEFAULT NULL,
  `question` text,
  `public_type` int(11) NOT NULL DEFAULT '1',
  `status` int(11) NOT NULL DEFAULT '1',
  `created_by` int(11) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `head` int(11) DEFAULT NULL,
  `sub_head` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
