CREATE TABLE IF NOT EXISTS `balance_confirmations_subject_values` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `element_id` int(11) NOT NULL,
  `element_name` varchar(250) NOT NULL,
  `subject_id` int(11) NOT NULL,
  `subject_name` varchar(250) NOT NULL,
  `execution_id` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `balance_as_per_book` double(10,2) NOT NULL,
  `balance_as_confirmed` double(10,2) NOT NULL,
  `bookbalance_as_on_date` date NOT NULL,
  `confirmedbalance_as_on_date` date NOT NULL,
  `difference` double(10,2) NOT NULL,
  `remarks` text NOT NULL,
  `reconciled` int(1) NOT NULL,
  `attachment_id` int(11) NOT NULL,
  `approved_by` int(11) NOT NULL,
  `approved_dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approver_user` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `status` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
