CREATE TABLE IF NOT EXISTS `uploadings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `domain_id` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `uploaded_by` int(11) NOT NULL,
  `uploaded_file_name` text NOT NULL,
  `original_file_name` varchar(255) DEFAULT NULL,
  `uploaded_file_path` text NOT NULL,
  `uploaded_file_size` varchar(250) NOT NULL,
  `uploaded_dt_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uploaded_file_type` varchar(250) NOT NULL,
  `uploaded_on_functionality` varchar(250) NOT NULL COMMENT 'tools,plans,taskupdates....',
  `workingpaper_category` int(11) NOT NULL,
  `workingpaper_subcategory` int(11) NOT NULL,
  `ass_seq_id` int(11) NOT NULL,
  `ass_seq_txt` varchar(15) NOT NULL,
  `timeline_id` int(5) NOT NULL,
  `description` text NOT NULL,
  `bucket` varchar(255) DEFAULT NULL,
  `bucketkey` varchar(255) DEFAULT NULL,
  `bucketkey_csv` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
