CREATE TABLE IF NOT EXISTS `checklist_node_client_level` (
  `checklist_node_id` int(11) NOT NULL AUTO_INCREMENT,
  `checklist_id` int(11) NOT NULL,
  `parent_nodeid` int(11) NOT NULL,
  `short_checklist` text NOT NULL,
  `full_checklist` text NOT NULL,
  `nodelevel` int(11) NOT NULL,
  `nodecode` varchar(80) NOT NULL,
  `level1` int(11) NOT NULL,
  `level2` int(11) NOT NULL,
  `level3` int(11) NOT NULL,
  `level4` int(11) NOT NULL,
  `level5` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `master_id` int(11) NOT NULL,
  `master_parent_id` int(11) NOT NULL,
  `desired_result` tinyint(1) NOT NULL,
  `na_as` tinyint(1) NOT NULL,
  `answer_type` int(4) NOT NULL DEFAULT '0' COMMENT '0 - No validation\r\n1 - Numeric(without decimal)\r\n2 - Numeric(with decimal)\r\n3 - Date\r\n4 - selection\r\n5 - phone\r\n6 - email\r\n7 - pan\r\n8 - aadhar\r\n9 - GST\r\n10 - alpha numeric',
  `answer_type_selection_id` int(11) NOT NULL COMMENT 'if answer type selection then selection_id is saved here',
  `sr_no` int(11) DEFAULT NULL,
  `order_no` int(11) DEFAULT NULL,
  `falling_under` int(11) DEFAULT NULL,
  `client_id` int(5) NOT NULL,
  `assignment_id` int(5) NOT NULL,
  `client_assignment_type` int(1) NOT NULL COMMENT '1=client,2=assignment',
  `node_code` varchar(255) DEFAULT NULL,
  `node_level` int(11) DEFAULT NULL,
  `node_sequence` int(11) DEFAULT NULL,
  PRIMARY KEY (`checklist_node_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
