CREATE TABLE IF NOT EXISTS `scheduler_template` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `activity_name` text NOT NULL,
  `activity_type` varchar(100) NOT NULL,
  `table_name` varchar(50) NOT NULL,
  `record_id` int(11) NOT NULL,
  `timeline_id` int(11) NOT NULL,
  `dur_hrs` varchar(10) NOT NULL,
  `est_start_date` date NOT NULL,
  `est_end_date` date NOT NULL,
  `es` int(11) NOT NULL,
  `ef` int(11) NOT NULL,
  `ls` int(11) NOT NULL,
  `lf` int(11) NOT NULL,
  `critical_path` varchar(4) NOT NULL COMMENT 'yes,no',
  `template_id` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` date NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_on` date NOT NULL,
  `taskHead_id` int(11) NOT NULL,
  `task_list_id` int(11) NOT NULL,
  `perc_val` varchar(100) NOT NULL,
  `workid` int(11) NOT NULL,
  `task_status` int(11) NOT NULL,
  `status_change_dt` datetime NOT NULL,
  `due_date` date NOT NULL,
  `status` int(11) NOT NULL DEFAULT '1',
  `est_hrs` float(5,2) NOT NULL,
  `poc` double(5,2) NOT NULL,
  `avalue` double(10,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
