CREATE TABLE IF NOT EXISTS `balance_confirmation` (
  `bid` int(11) NOT NULL AUTO_INCREMENT,
  `Client_id` int(5) NOT NULL,
  `assignment_id` int(5) NOT NULL,
  `domain_id` int(5) NOT NULL,
  `audit_procedure_id` int(5) NOT NULL,
  `chapter_id` int(5) NOT NULL,
  `name_party` varchar(250) NOT NULL,
  `amount` float NOT NULL,
  `confirmation` int(1) NOT NULL,
  `amt_confirmed` float NOT NULL,
  `full_amt_confirmation` int(1) NOT NULL,
  `remarks` text NOT NULL,
  `remarks_auditor` text NOT NULL,
  `vendor` varchar(250) NOT NULL,
  `approver_user` int(5) NOT NULL,
  `doer_user` int(5) NOT NULL,
  `created_by` int(5) NOT NULL,
  `created_on` date NOT NULL,
  `date_confirmation` date NOT NULL,
  `approved_status` int(1) NOT NULL,
  `approved_by` int(5) NOT NULL,
  `approved_on` date NOT NULL,
  PRIMARY KEY (`bid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
