CREATE TABLE IF NOT EXISTS `assets` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gl_id` int(11) NOT NULL,
  `proposal_id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `asset_name` varchar(200) NOT NULL,
  `type_asset` varchar(200) NOT NULL,
  `asset_id` varchar(50) NOT NULL,
  `asset_location` int(11) NOT NULL,
  `date_purchase` date NOT NULL,
  `strata_A` int(11) NOT NULL,
  `strata_B` int(11) NOT NULL,
  `strata_C` int(11) NOT NULL,
  `strata_D` int(11) NOT NULL,
  `strata_E` int(11) NOT NULL,
  `answer` text NOT NULL,
  `given_status` int(11) NOT NULL COMMENT '	1-not initiated,2-submitted,3-rejected,4-approved',
  `given_dt` date NOT NULL,
  `given_by` int(11) NOT NULL,
  `approved_on` date NOT NULL,
  `approved_by` int(11) NOT NULL,
  `execution_id` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_date` date NOT NULL,
  `modified_by` int(11) NOT NULL,
  `modified_date` date NOT NULL,
  `filter_l` int(11) NOT NULL,
  `filter_m` int(11) NOT NULL,
  `filter_n` int(11) NOT NULL,
  `filter_o` int(11) NOT NULL,
  `filter_p` int(11) NOT NULL,
  `materialized_val` int(11) NOT NULL COMMENT '0-no,1-yes',
  `master_company_id` int(11) NOT NULL,
  `igst` double(10,2) NOT NULL,
  `cgst` double(10,2) NOT NULL,
  `sgst` double(10,2) NOT NULL,
  `cess` double(10,2) NOT NULL,
  `remarks` text NOT NULL,
  `transaction_id` int(11) NOT NULL,
  `transaction_details_id` int(11) NOT NULL,
  `batchno` int(11) NOT NULL,
  `temp_code` varchar(250) NOT NULL,
  `other1` int(11) NOT NULL,
  `other2` text NOT NULL,
  `other3` date NOT NULL,
  `gl_name` varchar(200) NOT NULL,
  `counterparty_name` varchar(250) NOT NULL,
  `counterparty_gstin` varchar(250) NOT NULL,
  `voucher_no` varchar(200) NOT NULL,
  `type_of_supply1` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `proposal_id` (`proposal_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
