CREATE TABLE IF NOT EXISTS `gl_list` (
  `gl_id` int(11) NOT NULL AUTO_INCREMENT,
  `gl_name` varchar(250) NOT NULL,
  `previous_amount` float DEFAULT NULL,
  `present_amount` float DEFAULT NULL,
  `cao_id` int(11) DEFAULT NULL,
  `fss_id` int(11) DEFAULT NULL,
  `cos_id` int(11) DEFAULT NULL,
  `gl_code` varchar(250) DEFAULT NULL,
  `remarks` text NOT NULL,
  `fss_dummy` varchar(250) NOT NULL,
  `coa_dummy` text NOT NULL,
  `cos_dummy` varchar(250) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `strata_A` int(11) NOT NULL,
  `strata_B` int(11) NOT NULL,
  `strata_C` int(11) NOT NULL,
  `strata_D` int(11) NOT NULL,
  `strata_E` int(11) NOT NULL,
  `answer` text NOT NULL,
  `given_status` int(11) NOT NULL COMMENT '1-not initiated,2-submitted,3-rejected,4-approved',
  `given_dt` date NOT NULL,
  `given_by` int(11) NOT NULL,
  `approved_on` date NOT NULL,
  `approved_by` int(11) NOT NULL,
  `execution_id` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `created_date` date NOT NULL,
  `modified_by` int(11) NOT NULL,
  `modified_date` date NOT NULL,
  `batchno` int(11) NOT NULL,
  `other1` varchar(250) NOT NULL,
  `other2` varchar(250) NOT NULL,
  `other3` varchar(250) NOT NULL,
  `link_id` int(11) NOT NULL COMMENT 'link to previous gl list id',
  `sum_trial_balance` double DEFAULT NULL,
  `status_of_approval` int(11) NOT NULL,
  `daybook_gl_id` int(11) NOT NULL,
  PRIMARY KEY (`gl_id`),
  UNIQUE KEY `gl_code` (`gl_code`,`assignment_id`),
  KEY `fss_id` (`fss_id`),
  KEY `assignment_id` (`assignment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
