CREATE TABLE IF NOT EXISTS `gl_trial_balance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `transaction_id` bigint(20) NOT NULL,
  `classification_type` enum('FSS','COA','COS') NOT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `gl_id` int(11) NOT NULL,
  `mode` enum('FROM','TO') NOT NULL,
  `location_id` bigint(20) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` varchar(250) NOT NULL,
  `gl_code` varchar(250) NOT NULL,
  `gl_dummy` varchar(250) NOT NULL,
  `loc_dummy` varchar(250) NOT NULL,
  `remarks` text NOT NULL,
  `batchno` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `strata_A` int(11) NOT NULL,
  `strata_B` int(11) NOT NULL,
  `strata_C` int(11) NOT NULL,
  `strata_D` int(11) NOT NULL,
  `strata_E` int(11) NOT NULL,
  `filter_l` int(11) NOT NULL,
  `filter_m` int(11) NOT NULL,
  `filter_n` int(11) NOT NULL,
  `filter_o` int(11) NOT NULL,
  `filter_p` int(11) NOT NULL,
  `materialized_val` int(11) NOT NULL COMMENT '0-no,1-yes',
  `other1` varchar(250) NOT NULL,
  `other2` varchar(250) NOT NULL,
  `other3` varchar(250) NOT NULL,
  `sum_rectification` double DEFAULT NULL,
  `sum_grand_total` double DEFAULT NULL,
  `opening_balance` decimal(20,2) DEFAULT NULL,
  `debit` decimal(20,2) DEFAULT NULL,
  `credit` decimal(20,2) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `status_of_approval` int(11) NOT NULL,
  `approved_by` int(11) NOT NULL,
  `approved_on` date NOT NULL,
  `daybook_gl_id` int(11) NOT NULL,
  `daybook_netamt` double(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `assignment_id` (`assignment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
