
DROP TABLE IF EXISTS `other_procedures`;

CREATE TABLE IF NOT EXISTS `other_procedures` (
  `opid` int(11) NOT NULL AUTO_INCREMENT,
  `opname` varchar(250) NOT NULL,
  `field` int(11) NOT NULL COMMENT '1-Blue,2-Green',
  `controllername` varchar(250) NOT NULL,
  `func_name` varchar(250) NOT NULL,
  `chapter_id` int(11) NOT NULL,
  PRIMARY KEY (`opid`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=latin1;


INSERT INTO `other_procedures` (`opid`, `opname`, `field`, `controllername`, `func_name`, `chapter_id`) VALUES
(1, 'Audit Materiality', 2, '', '', 4),
(2, 'Financial_Statements', 2, '', '', 2),
(3, 'Financials_master', 2, '', '', 3),
(4, 'Permanent File', 2, '', '', 2),
(5, 'Audit Facts for Decisions', 2, '', '', 1),
(6, '', 2, '', '', 2),
(7, '', 2, '', '', 1),
(8, '', 2, '', '', 1),
(9, '', 2, '', '', 1),
(10, 'Current File', 2, '', '', 1),
(11, '', 2, '', '', 1),
(12, '', 2, '', '', 1),
(13, '', 2, '', '', 1),
(14, '', 2, '', '', 2),
(15, 'Audit of Inventory', 2, 'AuditProcedures', 'audit_inventory_1', 1),
(16, 'Audit of Revenue', 2, 'AuditProcedures', 'audit_inventory_2', 2),
(17, 'Audit of Payment to Employees', 2, 'AuditProcedures', 'audit_inventory_3', 4),
(18, 'Audit of Expenses', 2, 'AuditProcedures', 'audit_inventory_4', 2),
(19, 'Audit of Property,Plant,Equipment&Depreciation', 2, 'AuditProcedures', 'audit_inventory_5', 4),
(20, 'Audit of Borrowings & Borrowing Cost', 2, 'AuditProcedures', 'audit_inventory_6', 1),
(21, 'Audit of Investments & Other Assets', 2, 'AuditProcedures', 'audit_inventory_7', 3),
(22, 'Audit of Non-operational Income& Expenses', 2, 'AuditProcedures', 'audit_inventory_8', 2),
(23, 'Audit of Current Tax and Deferred tax', 2, 'AuditProcedures', 'audit_inventory_9', 4),
(24, 'Audit of Cash and Bank Balances', 2, 'AuditProcedures', 'audit_inventory_10', 2),
(25, 'Audit of Share Capital & Reserves', 2, 'AuditProcedures', 'audit_inventory_11', 1),
(26, 'Audit of Capital Commitment & Contingent liabilities', 2, 'AuditProcedures', 'audit_inventory_12', 2),
(27, 'Audit of Account Receivable & Payable', 2, 'AuditProcedures', 'audit_inventory_13', 3),
(28, 'Audit of Other Liabilities', 2, 'AuditProcedures', 'audit_inventory_14', 2),
(29, 'Audit of Exceptional Items', 2, 'AuditProcedures', 'audit_inventory_15', 4),
(30, 'Audit Acceptance', 2, 'AcceptanceInitiation', 'auditacceptance', 1),
(31, 'Audit Initiation', 2, 'AcceptanceInitiation', 'auditinitiation', 4),
(32, 'Knowledge of the Business', 2, 'AcceptanceInitiation', 'knowledgebusiness', 2),
(33, 'Engagement Risk Assessment', 2, 'AcceptanceInitiation', 'engagementrisk', 3),
(34, 'Management Representation', 2, '', '', 2),
(35, 'Going Concern', 2, 'AcceptanceInitiation', 'goingconcern', 1),
(36, 'Subsequent Events', 2, 'AcceptanceInitiation', 'sibsequentevents', 2),
(37, 'Collection of Audit Facts', 2, '', '', 4),
(38, 'Data Collection', 2, '', '', 2),
(39, 'Data Analytics', 2, '', '', 3),
(40, 'Audit of Advances (Banks)', 2, 'AuditProcedures', 'audit_inventory_26', 1),
(41, 'Fss_Risk_Assessment', 2, '', '', 4),
(42, 'Fss_Tb', 2, '', '', 2),
(43, 'Fss_Chart_of_Accounts', 2, '', '', 4),
(44, 'Icofar_Riskassessment', 2, '', '', 2),
(45, 'Icofar_Process_management', 2, '', '', 1),
(46, 'Audit Memo', 2, '', '', 1),
(47, 'Audit Notes', 2, '', '', 1),
(48, 'Audit Communication', 2, '', '', 1),
(49, 'Finding By Others', 2, '', '', 1),
(50, 'Working paper Attachments', 2, '', '', 1);
COMMIT;
