CREATE TABLE IF NOT EXISTS `p_exp_leadsheet` (
  `pae_id` int(11) NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) NOT NULL,
  `power_fuel` double(15,2) NOT NULL,
  `stores_spares` double(15,2) NOT NULL,
  `factory_overheads` double(15,2) NOT NULL,
  `others_manufacturing` double(15,2) NOT NULL,
  `manufacturing` double(15,2) NOT NULL,
  `business_promotion_expenses` double(15,2) NOT NULL,
  `brokerage_commission` double(15,2) NOT NULL,
  `carriage_outwards` double(15,2) NOT NULL,
  `others_selling` double(15,2) NOT NULL,
  `selling_distribution` double(15,2) NOT NULL,
  `rentals` double(15,2) NOT NULL,
  `rates_taxes` double(15,2) NOT NULL,
  `audit_fees` double(15,2) NOT NULL,
  `insurance` double(15,2) NOT NULL,
  `penalties` double(15,2) NOT NULL,
  `bad_debts` double(15,2) NOT NULL,
  `professional_charges` double(15,2) NOT NULL,
  `legal_expenses` double(15,2) NOT NULL,
  `others_administration` double(15,2) NOT NULL,
  `administration_expenses` double(15,2) NOT NULL,
  `status` int(2) NOT NULL,
  `doer_user` int(11) NOT NULL,
  `approver_user` int(11) NOT NULL,
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` date NOT NULL,
  PRIMARY KEY (`pae_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
