CREATE TABLE IF NOT EXISTS `library_details` (
  `book_id` int(11) NOT NULL AUTO_INCREMENT,
  `book` varchar(250) NOT NULL,
  `isbn` varchar(250) NOT NULL,
  `pages` varchar(100) NOT NULL,
  `author` varchar(250) NOT NULL,
  `publisher` varchar(250) NOT NULL,
  `edition` varchar(100) NOT NULL,
  `year_publication` varchar(100) NOT NULL,
  `volume` varchar(100) NOT NULL,
  `subject` int(11) NOT NULL,
  `category` int(11) NOT NULL,
  `sub_category` int(11) NOT NULL,
  `location` int(11) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` varchar(20) NOT NULL,
  `book_code` varchar(100) NOT NULL,
  `placement_no` varchar(100) NOT NULL,
  `book_size` int(11) NOT NULL,
  `domain` int(11) NOT NULL,
  `status_approval` int(11) NOT NULL DEFAULT '0' COMMENT '0=no status,1=requested,2=Cancelled request,3=issued,4=returned,5=confirmed return,6=cancelled confirmation return 7- Approved Request(After 1 )',
  `movement_ref_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`book_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
