CREATE TABLE IF NOT EXISTS `bills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client` int(11) NOT NULL,
  `assignment` int(11) NOT NULL,
  `timeline` int(11) NOT NULL,
  `bill_amount` varchar(100) NOT NULL,
  `remarks` text NOT NULL,
  `attachment` varchar(250) NOT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` date NOT NULL,
  `status` varchar(5) NOT NULL COMMENT '1=to be raised,2=bill raised,3=money received,3.5=first amount received,4=closed',
  `bill_raised_by` int(11) NOT NULL,
  `bill_raised_on` date NOT NULL,
  `raised_attachment` varchar(250) NOT NULL,
  `bill_no` varchar(250) NOT NULL,
  `domain` int(11) NOT NULL,
  `proposed_amount` varchar(50) NOT NULL,
  `bill_type` int(11) NOT NULL COMMENT '1=Receipt,2=Payment',
  `gst_amount` varchar(20) NOT NULL,
  `total_amount` varchar(20) NOT NULL,
  `account_head_id` int(11) NOT NULL DEFAULT '0' COMMENT 'join from accounting_heads table',
  PRIMARY KEY (`id`),
  KEY `bill_type` (`bill_type`),
  KEY `domain` (`domain`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
