CREATE TABLE IF NOT EXISTS `domains` (
  `did` int(11) NOT NULL AUTO_INCREMENT,
  `domain_name` varchar(250) NOT NULL,
  `description` varchar(250) NOT NULL,
  `creation_dt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `domain_logo` varchar(250) NOT NULL,
  `subscription_planid` int(11) NOT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `domain_head` varchar(250) NOT NULL,
  `domain_head_pwd` varchar(250) NOT NULL,
  `head_phno` bigint(20) NOT NULL,
  `head_email` varchar(250) NOT NULL,
  `all_user_count` int(11) NOT NULL,
  `active_user_count` int(11) NOT NULL,
  `client_count` int(11) NOT NULL,
  `assignment_count` int(11) NOT NULL,
  `db_name` varchar(250) NOT NULL,
  `db_user` varchar(250) NOT NULL,
  `db_pwd` varchar(250) NOT NULL,
  `data_size` double(10,2) NOT NULL COMMENT 'in MB',
  `dt_of_expiry` date NOT NULL,
  PRIMARY KEY (`did`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
