CREATE TABLE IF NOT EXISTS `cos_list_custom` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cos_node_id` int(11) NOT NULL,
  `cos_id` int(11) NOT NULL,
  `parent_nodeid` int(11) NOT NULL,
  `short_cos` varchar(250) NOT NULL,
  `full_cos` text NOT NULL,
  `base` int(11) NOT NULL,
  `type_value` varchar(250) NOT NULL COMMENT 'Income,Expenditure,Asset,Liability',
  `nodelevel` int(11) NOT NULL,
  `nodecode` varchar(80) NOT NULL,
  `level1` int(11) NOT NULL,
  `level2` int(11) NOT NULL,
  `level3` int(11) NOT NULL,
  `level4` int(11) NOT NULL,
  `level5` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `domain_id` int(11) NOT NULL,
  `master_link_id` int(11) NOT NULL,
  `prev_link_id` int(11) NOT NULL,
  `gl_list_total` float DEFAULT NULL,
  `gl_rectify_total` float DEFAULT NULL,
  `gl_reclassify_total` float DEFAULT NULL,
  `grand_total` float DEFAULT NULL,
  `specific_materiality` double(15,2) NOT NULL,
  `effective_materiality` double(15,2) NOT NULL,
  `risk_score` double(15,2) NOT NULL,
  `open_risk_score` double(15,2) NOT NULL,
  `control_score` double(15,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
