CREATE TABLE IF NOT EXISTS `dc_overdues` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(5) DEFAULT NULL,
  `amount_irregularity` double(20,2) DEFAULT NULL,
  `assignment_id` int(5) DEFAULT NULL,
  `client_id` int(5) DEFAULT NULL,
  `domain_id` int(5) DEFAULT NULL,
  `from_date` date DEFAULT NULL,
  `to_date` date DEFAULT NULL,
  `remarks` text,
  `created_by` int(5) NOT NULL,
  `creation_on` date NOT NULL,
  `audit_procedure_id` int(5) NOT NULL,
  `chapter_id` int(5) NOT NULL,
  `approver_user` int(5) NOT NULL,
  `doer_user` int(5) NOT NULL,
  `status` int(1) NOT NULL,
  `attachment_id` int(5) NOT NULL,
  `strata_A` int(11) DEFAULT NULL,
  `strata_B` int(11) DEFAULT NULL,
  `strata_C` int(11) DEFAULT NULL,
  `strata_D` int(11) DEFAULT NULL,
  `strata_E` int(11) DEFAULT NULL,
  `filter_l` int(11) DEFAULT NULL,
  `filter_m` int(11) DEFAULT NULL,
  `filter_n` int(11) DEFAULT NULL,
  `filter_o` int(11) DEFAULT NULL,
  `filter_p` int(11) DEFAULT NULL,
  `materiality` int(11) DEFAULT NULL,
  `batchno` int(11) DEFAULT NULL,
  `temp_code` varchar(250) DEFAULT NULL,
  `name` varchar(250) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `assignment_id` (`assignment_id`),
  KEY `assignment_id_2` (`assignment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
