CREATE TABLE IF NOT EXISTS `agreement_assignment_nodeds` (
  `node_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_nodeid` int(11) NOT NULL,
  `head_id` int(11) NOT NULL,
  `short` varchar(250) NOT NULL,
  `full` text NOT NULL,
  `answer` text NOT NULL,
  `nodelevel` int(11) NOT NULL,
  `nodecode` varchar(80) NOT NULL,
  `level1` int(11) NOT NULL,
  `level2` int(11) NOT NULL,
  `level3` int(11) NOT NULL,
  `level4` int(11) NOT NULL,
  `level5` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `risk_score` double(10,2) DEFAULT NULL,
  `control_score` double(10,2) DEFAULT NULL,
  `total_score` double(10,2) DEFAULT NULL,
  `open_risk_score` double(10,2) DEFAULT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `domain_id` int(11) NOT NULL,
  `link_id` int(11) NOT NULL,
  `control_owner` int(11) NOT NULL,
  `node_code` varchar(255) DEFAULT NULL,
  `node_level` int(11) DEFAULT NULL,
  `node_sequence` int(11) DEFAULT NULL,
  PRIMARY KEY (`node_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
