CREATE TABLE IF NOT EXISTS `activity_risk_control` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `control_name` varchar(150) NOT NULL,
  `type` varchar(150) NOT NULL,
  `freq` varchar(150) NOT NULL,
  `owner` varchar(250) NOT NULL,
  `automation` varchar(150) NOT NULL,
  `description` text NOT NULL,
  `creationdt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `risk_id` int(11) NOT NULL,
  `activity_id` int(11) NOT NULL,
  `activity_risk_id` int(11) NOT NULL,
  `existence_of_control` double(5,2) NOT NULL COMMENT 'percentage',
  `effectiveness_of_control` double(5,2) NOT NULL COMMENT 'percentage',
  `weightage` double(10,2) DEFAULT NULL,
  `control_rating` varchar(250) NOT NULL,
  `pagetype` int(11) NOT NULL COMMENT '1=process,2=workflow,3=agreement',
  `category` int(11) NOT NULL,
  `audit_response_id` int(11) NOT NULL,
  `client_id` int(11) NOT NULL,
  `assignment_id` int(11) NOT NULL,
  `domain_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
